### ISSUE TITLE
TypeScript 2.9 support

### ISSUE THREAD

**Issue by mprobst** [angular/zone.js#1104]
Zone JS doesn't compile with TypeScript 2.9:

```
v0_8_16/lib/browser/define-property.ts:24:70 - error TS2469: The '+' operator cannot be applied to type 'symbol'.

24       throw new TypeError('Cannot assign to read only property \'' + prop + '\' of ' + obj);
                                                                        ~~~~
v0_8_16/lib/browser/define-property.ts:28:37 - error TS2345: Argument of type 'string | number | symbol' is not assignable to parameter of type 'string'.
  Type 'number' is not assignable to type 'string'.

28       desc = rewriteDescriptor(obj, prop, desc);
                                       ~~~~
v0_8_16/lib/browser/define-property.ts:30:36 - error TS2345: Argument of type 'string | number | symbol' is not assignable to parameter of type 'string'.
  Type 'number' is not assignable to type 'string'.

30     return _tryDefineProperty(obj, prop, desc, originalConfigurableFlag);
                                      ~~~~
```

**Comment by mprobst** [comment]
(note: this is using v0.8.16, but it looks as if the compile errors are still current)

**Comment by JiaLiPassion** [comment]
I did some modification in other PR, I will check that PR can pass TS 2.9 or not.

**Comment by JiaLiPassion** [comment]
This has already been fixed.
